# Generated by Django 3.0.5 on 2020-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200419_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='max_value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='min_value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
