# Generated by Django 3.0.5 on 2020-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longtitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sensor_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.SensorLocation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateField(auto_now_add=True)),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.SensorType')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
